# Generated by Django 5.0.7 on 2024-07-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tricount', '0005_remove_expense_participants_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
