# Generated by Django 5.0.7 on 2024-07-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricount', '0006_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantpayment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='group',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='memberbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_payments', to='tricount.expense'),
        ),
    ]
