# Generated by Django 5.0.7 on 2024-07-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricount', '0007_rename_amount_participantpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantpayment',
            old_name='participant',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='participantpayment',
            name='expense',
        ),
        migrations.AddField(
            model_name='participantpayment',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tricount.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
