# Generated by Django 5.0.7 on 2024-07-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tricount', '0010_remove_receipt_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='total_amount',
        ),
    ]
