version: '3.7'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 nom_du_projet.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=nom_du_projet.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/dbname

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
