version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 tricount.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=tricount.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
